app.service:
  name: 'QA profile:'

server:
  port: 8090

spring:
  profiles: api-qa
  rabbitmq:
    host: rmq.qa.emx.lhdip.com
    port: 5672
    username: emxadmin
    password: liquid123+

spring.datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://db.dev.emx.lhdip.com:1433;databaseName=emx-qa
    username: emx-dev
    password: liquid123+

# YML Code for setting up the Log file Goes here
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    com.integration: INFO
    org.hibernate: ERROR
  file: logs/emx-api-app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
    
